"""add_users_table

Revision ID: 59e827f8761d
Revises: e33ed8b10be4
Create Date: 2025-07-09 15:33:23.778309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import bluenote.schemas.common


# revision identifiers, used by Alembic.
revision: str = '59e827f8761d'
down_revision: Union[str, None] = 'e33ed8b10be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('require_password_change', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', bluenote.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('updated_at', bluenote.schemas.common.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
