"""Change photos tags and url_list from JSON to TEXT

Revision ID: 85edf7a928d1
Revises: b03e07d4530a
Create Date: 2025-07-20 22:25:34.373102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '85edf7a928d1'
down_revision: Union[str, None] = 'b03e07d4530a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('url_list',
                   existing_type=sqlite.JSON(),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.alter_column('tags',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Text(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('tags',
                   existing_type=sa.Text(),
                   type_=sa.VARCHAR(),
                   existing_nullable=True)
        batch_op.alter_column('url_list',
                   existing_type=sa.Text(),
                   type_=sqlite.JSON(),
                   existing_nullable=True)
    # ### end Alembic commands ###
