"""Change tags field from JSON to TEXT

Revision ID: b03e07d4530a
Revises: 5a4463440d74
Create Date: 2025-07-20 22:16:49.038929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b03e07d4530a'
down_revision: Union[str, None] = '5a4463440d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite不支持ALTER COLUMN TYPE，使用重建表的方式
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('tags',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('tags',
                   existing_type=sa.Text(),
                   type_=sa.VARCHAR(),
                   existing_nullable=True)
        batch_op.add_column(sa.Column('meta_description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
