"""Update photos table: replace url with url_list and remove image metadata fields

Revision ID: cd222181b027
Revises: c0acb67fec2f
Create Date: 2025-07-15 09:55:10.609972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd222181b027'
down_revision: Union[str, None] = '59e827f8761d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('url_list', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('photos', 'url')
    op.drop_column('photos', 'width')
    op.drop_column('photos', 'file_size')
    op.drop_column('photos', 'format')
    op.drop_column('photos', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('photos', 'url_list')
    # ### end Alembic commands ###
